const RouteWatcher = "@/components/page_tab/RouteWatcher";
export default [
  {
    name: "tool",
    icon: "BugOutlined",
    path: "/tool",

    routes: [
      {
        path: "/",
        redirect: "/tool/gen",
      },
      {
        name: "gen",
        icon: "PartitionOutlined",
        path: "/tool/gen",
        component: "tool/gen/index",
        access: "authorize",
        wrappers: [RouteWatcher],
        title: "menu.title.gen",
      },
      {
        name: "design",
        icon: "PartitionOutlined",
        path: "/tool/build",
        component: "tool/builder",
        access: "authorize",
        wrappers: [RouteWatcher],
        title: "menu.title.design",
      },
      {
        name: "swagger",
        icon: "PartitionOutlined",
        path: "/tool/swagger",
        component: "tool/swagger",
        access: "authorize",
        wrappers: [RouteWatcher],
        //KeepAlive: true,
        title: "menu.title.swagger",
      },
      {
        name: "test",
        icon: "PartitionOutlined",
        path: "/tool/test",
        component: "tool/test",
        access: "authorize",
        wrappers: [RouteWatcher],
        title: "menu.title.test",
      },
      {
        name: "calendar",
        icon: "PartitionOutlined",
        path: "/tool/calendar",
        component: "tool/calendar",
        access: "authorize",
        wrappers: [RouteWatcher],
        title: "menu.title.calendar",
      },
    ],
  },
  {
    name: "system",
    icon: "BugOutlined",
    path: "/system",

    routes: [
      {
        path: "/",
        redirect: "/system/user",
      },
      {
        name: "user",
        icon: "PartitionOutlined",
        path: "/system/user",
        component: "system/user/index",
        access: "authorize",
      },
      {
        name: "menu",
        icon: "PartitionOutlined",
        path: "/system/menu",
        component: "system/menu/index",
        access: "authorize",
      },
      {
        name: "role",
        icon: "PartitionOutlined",
        path: "/system/role",
        component: "system/role/index",
        access: "authorize",
        ////wrappers: ['@/components/KeepAlive'],
        //KeepAlive: true,
        title: "menu.title.role",
      },
      {
        name: "dept",
        icon: "PartitionOutlined",
        path: "/system/dept",
        component: "system/dept/index",
        access: "authorize",
        ////wrappers: ['@/components/KeepAlive'],
        //KeepAlive: true,
        title: "menu.title.dept",
      },
      {
        name: "post",
        icon: "PartitionOutlined",
        path: "/system/post",
        component: "system/post/index",
        access: "authorize",
        ////wrappers: ['@/components/KeepAlive'],
        //KeepAlive: true,
        title: "menu.title.post",
      },
      {
        name: "dict",
        icon: "PartitionOutlined",
        path: "/system/dict",
        component: "system/dict/index",
        access: "authorize",
        ////wrappers: ['@/components/KeepAlive'],
        //KeepAlive: true,
        title: "menu.title.dict",
      },
      {
        name: "dictData",
        icon: "PartitionOutlined",
        path: "/system/dict-data/index/:id?",
        component: "system/dictData/index",
        access: "authorize",
        ////wrappers: ['@/components/KeepAlive'],
        //KeepAlive: true,
        title: "menu.title.dictData",
      },
      {
        name: "config",
        icon: "PartitionOutlined",
        path: "/system/config",
        component: "system/config/index",
        access: "authorize",
        ////wrappers: ['@/components/KeepAlive'],
        //KeepAlive: true,
        title: "menu.title.config",
      },
      {
        name: "notice",
        icon: "PartitionOutlined",
        path: "/system/notice",
        component: "system/notice/index",
        access: "authorize",
        ////wrappers: ['@/components/KeepAlive'],
        //KeepAlive: true,
        title: "menu.title.notice",
      },
      // {
      //   name: 'log',
      //   icon: 'BugOutlined',
      //   path: '/system/log/',
      //   routes: [
      //     {
      //       path: '/',
      //       redirect: '/system/log/operlog',
      //     },
      //     {
      //       name: 'operlog',
      //       icon: 'PartitionOutlined',
      //       path: '/system/log/operlog',
      //       component: 'monitor/operlog',
      //       access: 'authorize',
      //       ////wrappers: ['@/components/KeepAlive'],
      //       //KeepAlive: true,
      //       title: 'menu.title.operlog',
      //     },
      //     {
      //       name: 'loginInfo',
      //       icon: 'PartitionOutlined',
      //       path: '/system/log/logininfor',
      //       component: 'monitor/logininfor',
      //       access: 'authorize',
      //       ////wrappers: ['@/components/KeepAlive'],
      //       //KeepAlive: true,
      //       title: 'menu.title.loginInfo',
      //     },
      //   ],
      // },
    ],
  },
  {
    path: "/user",
    layout: false,
    routes: [
      {
        path: "/user/login",
        layout: false,
        name: "login",
        component: "./user/Login",
      },
      {
        path: "/user",
        redirect: "/user/login",
      },
      {
        name: "register-result",
        icon: "smile",
        path: "/user/register-result",
        component: "./user/register-result",
      },
      {
        name: "register",
        icon: "smile",
        path: "/user/register",
        component: "./user/register",
      },
      {
        component: "404",
      },
    ],
  },
  {
    path: "/dashboard",
    name: "dashboard",
    icon: "dashboard",

    routes: [
      {
        path: "/dashboard",
        redirect: "/dashboard/analysis",
      },
      {
        name: "analysis",
        icon: "smile",
        path: "/dashboard/analysis",
        component: "./dashboard/analysis",
      },
      {
        name: "monitor",
        icon: "smile",
        path: "/dashboard/monitor",
        component: "./dashboard/monitor",
      },
      {
        name: "workplace",
        icon: "smile",
        path: "/dashboard/workplace",
        component: "./dashboard/workplace",
      },
    ],
  },
  {
    path: "/form",
    icon: "form",
    name: "form",
    routes: [
      {
        path: "/form",
        redirect: "/form/basic-form",
      },
      {
        name: "basic-form",
        icon: "smile",
        path: "/form/basic-form",
        access: "authorize",
        component: "./form/basic-form",
      },
      {
        name: "step-form",
        icon: "smile",
        path: "/form/step-form",
        access: "authorize",
        component: "./form/step-form",
      },
      {
        name: "advanced-form",
        icon: "smile",
        path: "/form/advanced-form",
        access: "authorize",
        component: "./form/advanced-form",
      },
    ],
  },
  {
    path: "/list",
    icon: "table",

    name: "list",
    routes: [
      {
        path: "/list/search",
        name: "search-list",
        component: "./list/search",
        routes: [
          {
            path: "/list/search",
            redirect: "/list/search/articles",
          },
          {
            name: "articles",
            icon: "smile",
            path: "/list/search/articles",
            component: "./list/search/articles",
          },
          {
            name: "projects",
            icon: "smile",
            path: "/list/search/projects",
            component: "./list/search/projects",
          },
          {
            name: "applications",
            icon: "smile",
            path: "/list/search/applications",
            component: "./list/search/applications",
          },
        ],
      },
      {
        path: "/list",
        redirect: "/list/table-list",
      },
      {
        name: "table-list",
        icon: "smile",
        path: "/list/table-list",
        component: "./list/table-list",
      },
      {
        name: "basic-list",
        icon: "smile",
        path: "/list/basic-list",
        component: "./list/basic-list",
      },
      {
        name: "card-list",
        icon: "smile",
        path: "/list/card-list",
        component: "./list/card-list",
      },
    ],
  },
  {
    path: "/profile",
    name: "profile",

    icon: "profile",
    routes: [
      {
        path: "/profile",
        redirect: "/profile/basic",
      },
      {
        name: "basic",
        icon: "smile",
        path: "/profile/basic",
        component: "./profile/basic",
      },
      {
        name: "advanced",
        icon: "smile",
        path: "/profile/advanced",
        component: "./profile/advanced",
      },
    ],
  },
  {
    name: "result",
    icon: "CheckCircleOutlined",
    path: "/result",
    routes: [
      {
        path: "/result",
        redirect: "/result/success",
      },
      {
        name: "success",
        icon: "smile",
        path: "/result/success",
        component: "./result/success",
      },
      {
        name: "fail",
        icon: "smile",
        path: "/result/fail",
        component: "./result/fail",
      },
    ],
  },
  {
    name: "exception",
    icon: "warning",
    path: "/exception",
    routes: [
      {
        path: "/exception",
        redirect: "/exception/403",
      },
      {
        name: "403",
        icon: "smile",
        path: "/exception/403",
        component: "./exception/403",
      },
      {
        name: "404",
        icon: "smile",
        path: "/exception/404",
        component: "./exception/404",
      },
      {
        name: "500",
        icon: "smile",
        path: "/exception/500",
        component: "./exception/500",
      },
    ],
  },
  {
    name: "account",
    icon: "user",
    path: "/account",
    routes: [
      {
        path: "/account",
        redirect: "/account/enter",
      },
      {
        name: "center",
        icon: "smile",
        path: "/account/center",
        component: "./account/center",
      },
      {
        name: "settings",
        icon: "smile",
        path: "/account/settings",
        component: "./account/settings",
      },
    ],
  },
  {
    name: "editor",
    icon: "highlight",
    path: "/editor",
    routes: [
      {
        path: "/editor",
        redirect: "/editor/flow",
      },
      {
        name: "flow",
        icon: "smile",
        path: "/editor/flow",
        component: "./editor/flow",
      },
      {
        name: "mind",
        icon: "smile",
        path: "/editor/mind",
        component: "./editor/mind",
      },
      {
        name: "koni",
        icon: "smile",
        path: "/editor/koni",
        component: "./editor/koni",
      },
    ],
  },
  {
    name: "monitor",
    icon: "BugOutlined",
    path: "/monitor",

    routes: [
      {
        path: "/",
        redirect: "/monitor/online",
      },
      {
        name: "onlineUser",
        icon: "PartitionOutlined",
        path: "/monitor/online",
        component: "monitor/online",
        access: "authorize",
        // //wrappers: ['@/components/KeepAlive'],
        //KeepAlive: true,
        title: "menu.title.onlineUser",
      },
      {
        name: "job",
        icon: "PartitionOutlined",
        path: "/monitor/job",
        component: "monitor/job",
        access: "authorize",
        // //wrappers: ['@/components/KeepAlive'],
        //KeepAlive: true,
        title: "menu.title.job",
      },
      {
        name: "joblog",
        icon: "PartitionOutlined",
        path: "/monitor/job-log/index/:jobId?",
        component: "monitor/joblog",
        access: "authorize",
        // //wrappers: ['@/components/KeepAlive'],
        //KeepAlive: true,
        title: "menu.title.joblog",
      },
      {
        name: "druid",
        icon: "PartitionOutlined",
        path: "/monitor/druid",
        component: "monitor/druid",
        access: "authorize",
        // //wrappers: ['@/components/KeepAlive'],
        //KeepAlive: true,
        // title: 'menu.title.druid',
      },
      {
        name: "serverInfo",
        icon: "PartitionOutlined",
        path: "/monitor/server",
        component: "monitor/server",
        access: "authorize",
        // //wrappers: ['@/components/KeepAlive'],
        //KeepAlive: true,
        title: "menu.title.serverInfo",
      },
      {
        name: "cacheInfo",
        icon: "PartitionOutlined",
        path: "/monitor/cache",
        component: "monitor/cache",
        access: "authorize",
        // //wrappers: ['@/components/KeepAlive'],
        //KeepAlive: true,
        title: "menu.title.cacheInfo",
      },
      {
        name: "cacheList",
        icon: "PartitionOutlined",
        path: "/monitor/cacheList",
        component: "monitor/cacheList",
        access: "authorize",
        // //wrappers: ['@/components/KeepAlive'],
        //KeepAlive: true,
        title: "menu.title.cacheList",
      },
    ],
  },
  {
    path: "/",
    redirect: "/dashboard/analysis",
  },
];
